scoreboard players set challengeChambersKeys global 1

summon area_effect_cloud ~ ~ ~ {Radius:0.0f,Duration:1000,Particle:"block air",Tags:[chunkLoader]}

execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1864 664 1 1 false @s
execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1864 648 1 1 false @s
execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1868 630 1 1 false @s
execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1877 620 1 1 false @s
execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1880 632 1 1 false @s
execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1896 632 1 1 false @s
execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1896 648 1 1 false @s
execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1896 664 1 1 false @s
execute as @e[tag=chunkLoader,limit=1,sort=nearest] at @s run spreadplayers 1880 664 1 1 false @s

execute unless score hasCollectedFlyingKey sharedQuests matches 1 run summon bat 1888 63 637 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["restorable","pickUp","flyingKey1","glowable","interactable","keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1321}}]}]}
summon bat 1882 39 651 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1879 42 656 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1879 44 640 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1882 45 631 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1870 50 631 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1886 48 636 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1890 41 640 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1898 43 637 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1890 39 651 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1887 45 647 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1892 51 640 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1883 58 631 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1883 60 635 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1879 53 632 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1877 55 628 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1876 57 638 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1876 57 638 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1874 51 640 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]} 
summon bat 1873 52 645 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]} 
summon bat 1879 50 646 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]} 
summon bat 1880 57 645 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1873 61 643 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1885 58 645 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1891 56 644 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1893 59 637 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}
summon bat 1887 44 656 {PersistenceRequired:1,Silent:1b,Invulnerable:1b,Tags:["keyCreature","invisible"],Passengers:[{id:"minecraft:armor_stand",Invulnerable:1b,Small:0b,Marker:1b,Invisible:1b,Tags:["keyCreatureVisual"],ArmorItems:[{},{},{},{id:"minecraft:diamond_sword",Count:1b,tag:{Unbreakable:1b,Damage:1320}}]}]}

kill @e[tag=chunkLoader]