advancement revoke @s[scores={completedQuestID=1}] only hp:quests/the_letter_from_noone_completed
advancement grant @s[scores={completedQuestID=1}] only hp:quests/the_letter_from_noone_completed
advancement revoke @s[scores={completedQuestID=2}] only hp:quests/diagon_alley_completed
advancement grant @s[scores={completedQuestID=2}] only hp:quests/diagon_alley_completed
advancement revoke @s[scores={completedQuestID=3}] only hp:quests/gringotts_wizarding_bank_completed
advancement grant @s[scores={completedQuestID=3}] only hp:quests/gringotts_wizarding_bank_completed
advancement revoke @s[scores={completedQuestID=4}] only hp:quests/purchase_wand_completed
advancement grant @s[scores={completedQuestID=4}] only hp:quests/purchase_wand_completed
advancement revoke @s[scores={completedQuestID=5}] only hp:quests/purchase_school_books_completed
advancement grant @s[scores={completedQuestID=5}] only hp:quests/purchase_school_books_completed
advancement revoke @s[scores={completedQuestID=6}] only hp:quests/purchase_school_robes_completed
advancement grant @s[scores={completedQuestID=6}] only hp:quests/purchase_school_robes_completed
advancement revoke @s[scores={completedQuestID=7}] only hp:quests/platform_9_3_4_completed
advancement grant @s[scores={completedQuestID=7}] only hp:quests/platform_9_3_4_completed
advancement revoke @s[scores={completedQuestID=8}] only hp:quests/arrival_at_hogwarts_completed
advancement grant @s[scores={completedQuestID=8}] only hp:quests/arrival_at_hogwarts_completed
advancement revoke @s[scores={completedQuestID=9}] only hp:quests/common_room_completed
advancement grant @s[scores={completedQuestID=9}] only hp:quests/common_room_completed
advancement revoke @s[scores={completedQuestID=10}] only hp:quests/common_room_completed
advancement grant @s[scores={completedQuestID=10}] only hp:quests/common_room_completed
advancement revoke @s[scores={completedQuestID=11}] only hp:quests/common_room_completed
advancement grant @s[scores={completedQuestID=11}] only hp:quests/common_room_completed
advancement revoke @s[scores={completedQuestID=12}] only hp:quests/common_room_completed
advancement grant @s[scores={completedQuestID=12}] only hp:quests/common_room_completed
advancement revoke @s[scores={completedQuestID=13}] only hp:quests/toad_hunt_completed
advancement grant @s[scores={completedQuestID=13}] only hp:quests/toad_hunt_completed
advancement revoke @s[scores={completedQuestID=14}] only hp:quests/lumos_completed
advancement grant @s[scores={completedQuestID=14}] only hp:quests/lumos_completed
advancement revoke @s[scores={completedQuestID=15}] only hp:quests/stupefy_completed
advancement grant @s[scores={completedQuestID=15}] only hp:quests/stupefy_completed
advancement revoke @s[scores={completedQuestID=16}] only hp:quests/brackium_emendo_completed
advancement grant @s[scores={completedQuestID=16}] only hp:quests/brackium_emendo_completed
advancement revoke @s[scores={completedQuestID=17}] only hp:quests/alohomora_completed
advancement grant @s[scores={completedQuestID=17}] only hp:quests/alohomora_completed
advancement revoke @s[scores={completedQuestID=18}] only hp:quests/wingardium_leviosa_completed
advancement grant @s[scores={completedQuestID=18}] only hp:quests/wingardium_leviosa_completed
advancement revoke @s[scores={completedQuestID=19}] only hp:quests/bombarda_maxima_completed
advancement grant @s[scores={completedQuestID=19}] only hp:quests/bombarda_maxima_completed
advancement revoke @s[scores={completedQuestID=20}] only hp:quests/vera_verto_completed
advancement grant @s[scores={completedQuestID=20}] only hp:quests/vera_verto_completed
advancement revoke @s[scores={completedQuestID=21}] only hp:quests/expecto_patronum_completed
advancement grant @s[scores={completedQuestID=21}] only hp:quests/expecto_patronum_completed
advancement revoke @s[scores={completedQuestID=22}] only hp:quests/apparition_completed
advancement grant @s[scores={completedQuestID=22}] only hp:quests/apparition_completed
advancement revoke @s[scores={completedQuestID=23}] only hp:quests/golden_skull_completed
advancement grant @s[scores={completedQuestID=23}] only hp:quests/golden_skull_completed
advancement revoke @s[scores={completedQuestID=24}] only hp:quests/underground_library_completed
advancement grant @s[scores={completedQuestID=24}] only hp:quests/underground_library_completed
advancement revoke @s[scores={completedQuestID=25}] only hp:quests/one_mans_trash_completed
advancement grant @s[scores={completedQuestID=25}] only hp:quests/one_mans_trash_completed
advancement revoke @s[scores={completedQuestID=26}] only hp:quests/flying_lesson_completed
advancement grant @s[scores={completedQuestID=26}] only hp:quests/flying_lesson_completed
advancement revoke @s[scores={completedQuestID=27}] only hp:quests/herbology_completed
advancement grant @s[scores={completedQuestID=27}] only hp:quests/herbology_completed
advancement revoke @s[scores={completedQuestID=28}] only hp:quests/potions_completed
advancement grant @s[scores={completedQuestID=28}] only hp:quests/potions_completed
advancement revoke @s[scores={completedQuestID=29}] only hp:quests/extracurricular_learning_completed
advancement grant @s[scores={completedQuestID=29}] only hp:quests/extracurricular_learning_completed
advancement revoke @s[scores={completedQuestID=30}] only hp:quests/flying_completed
advancement grant @s[scores={completedQuestID=30}] only hp:quests/flying_completed
advancement revoke @s[scores={completedQuestID=31}] only hp:quests/monster_book_of_monsters_completed
advancement grant @s[scores={completedQuestID=31}] only hp:quests/monster_book_of_monsters_completed
advancement revoke @s[scores={completedQuestID=32}] only hp:quests/sewer_rats_completed
advancement grant @s[scores={completedQuestID=32}] only hp:quests/sewer_rats_completed
advancement revoke @s[scores={completedQuestID=33}] only hp:quests/unfriendly_competition_completed
advancement grant @s[scores={completedQuestID=33}] only hp:quests/unfriendly_competition_completed
advancement revoke @s[scores={completedQuestID=34}] only hp:quests/the_order_of_the_phoenix_completed
advancement grant @s[scores={completedQuestID=34}] only hp:quests/the_order_of_the_phoenix_completed
advancement revoke @s[scores={completedQuestID=35}] only hp:quests/azkaban_completed
advancement grant @s[scores={completedQuestID=35}] only hp:quests/azkaban_completed
advancement revoke @s[scores={completedQuestID=36}] only hp:quests/the_pensive_completed
advancement grant @s[scores={completedQuestID=36}] only hp:quests/the_pensive_completed
advancement revoke @s[scores={completedQuestID=37}] only hp:quests/toad_hunt_2_completed
advancement grant @s[scores={completedQuestID=37}] only hp:quests/toad_hunt_2_completed
advancement revoke @s[scores={completedQuestID=38}] only hp:quests/toad_hunt_3_completed
advancement grant @s[scores={completedQuestID=38}] only hp:quests/toad_hunt_3_completed
advancement revoke @s[scores={completedQuestID=39}] only hp:quests/toad_hunt_4_completed
advancement grant @s[scores={completedQuestID=39}] only hp:quests/toad_hunt_4_completed
advancement revoke @s[scores={completedQuestID=40}] only hp:quests/toad_hunt_5_completed
advancement grant @s[scores={completedQuestID=40}] only hp:quests/toad_hunt_5_completed
advancement revoke @s[scores={completedQuestID=41}] only hp:quests/toad_hunt_6_completed
advancement grant @s[scores={completedQuestID=41}] only hp:quests/toad_hunt_6_completed
advancement revoke @s[scores={completedQuestID=42}] only hp:quests/chamber_of_secrets_completed
advancement grant @s[scores={completedQuestID=42}] only hp:quests/chamber_of_secrets_completed
advancement revoke @s[scores={completedQuestID=43}] only hp:quests/mirror_of_erised_completed
advancement grant @s[scores={completedQuestID=43}] only hp:quests/mirror_of_erised_completed
advancement revoke @s[scores={completedQuestID=44}] only hp:quests/the_room_of_requirement_completed
advancement grant @s[scores={completedQuestID=44}] only hp:quests/the_room_of_requirement_completed
advancement revoke @s[scores={completedQuestID=45}] only hp:quests/hogsmeade_letter_delivery_completed
advancement grant @s[scores={completedQuestID=45}] only hp:quests/hogsmeade_letter_delivery_completed
advancement revoke @s[scores={completedQuestID=46}] only hp:quests/burrow_infestation_completed
advancement grant @s[scores={completedQuestID=46}] only hp:quests/burrow_infestation_completed
advancement revoke @s[scores={completedQuestID=47}] only hp:quests/training_ground_toads_completed
advancement grant @s[scores={completedQuestID=47}] only hp:quests/training_ground_toads_completed
advancement revoke @s[scores={completedQuestID=48}] only hp:quests/follow_the_spiders_completed
advancement grant @s[scores={completedQuestID=48}] only hp:quests/follow_the_spiders_completed
advancement revoke @s[scores={completedQuestID=49}] only hp:quests/london_delivery_completed
advancement grant @s[scores={completedQuestID=49}] only hp:quests/london_delivery_completed
advancement revoke @s[scores={completedQuestID=50}] only hp:quests/delinquent_daily_prophet_completed
advancement grant @s[scores={completedQuestID=50}] only hp:quests/delinquent_daily_prophet_completed
advancement revoke @s[scores={completedQuestID=51}] only hp:quests/antic_advertisement_completed
advancement grant @s[scores={completedQuestID=51}] only hp:quests/antic_advertisement_completed
advancement revoke @s[scores={completedQuestID=52}] only hp:quests/postponed_postage_completed
advancement grant @s[scores={completedQuestID=52}] only hp:quests/postponed_postage_completed
advancement revoke @s[scores={completedQuestID=53}] only hp:quests/snowman_supplies_completed
advancement grant @s[scores={completedQuestID=53}] only hp:quests/snowman_supplies_completed
advancement revoke @s[scores={completedQuestID=54}] only hp:quests/the_most_haunted_place_in_britain_completed
advancement grant @s[scores={completedQuestID=54}] only hp:quests/the_most_haunted_place_in_britain_completed
advancement revoke @s[scores={completedQuestID=55}] only hp:quests/curable_creature_consultation_completed
advancement grant @s[scores={completedQuestID=55}] only hp:quests/curable_creature_consultation_completed
advancement revoke @s[scores={completedQuestID=56}] only hp:quests/snipe_hunt_completed
advancement grant @s[scores={completedQuestID=56}] only hp:quests/snipe_hunt_completed
advancement revoke @s[scores={completedQuestID=57}] only hp:quests/riddle_riches_completed
advancement grant @s[scores={completedQuestID=57}] only hp:quests/riddle_riches_completed
advancement revoke @s[scores={completedQuestID=58}] only hp:quests/dungeon_delving_completed
advancement grant @s[scores={completedQuestID=58}] only hp:quests/dungeon_delving_completed
advancement revoke @s[scores={completedQuestID=59}] only hp:quests/hand_of_glory_completed
advancement grant @s[scores={completedQuestID=59}] only hp:quests/hand_of_glory_completed
advancement revoke @s[scores={completedQuestID=60}] only hp:quests/parchment_poverty_completed
advancement grant @s[scores={completedQuestID=60}] only hp:quests/parchment_poverty_completed
advancement revoke @s[scores={completedQuestID=61}] only hp:quests/submerged_shrub_completed
advancement grant @s[scores={completedQuestID=61}] only hp:quests/submerged_shrub_completed
advancement revoke @s[scores={completedQuestID=62}] only hp:quests/quidditch_squabble_completed
advancement grant @s[scores={completedQuestID=62}] only hp:quests/quidditch_squabble_completed
advancement revoke @s[scores={completedQuestID=63}] only hp:quests/kitchen_raid_completed
advancement grant @s[scores={completedQuestID=63}] only hp:quests/kitchen_raid_completed
advancement revoke @s[scores={completedQuestID=64}] only hp:quests/dubious_divination_completed
advancement grant @s[scores={completedQuestID=64}] only hp:quests/dubious_divination_completed
advancement revoke @s[scores={completedQuestID=65}] only hp:quests/frog_choir_quarrel_completed
advancement grant @s[scores={completedQuestID=65}] only hp:quests/frog_choir_quarrel_completed
advancement revoke @s[scores={completedQuestID=66}] only hp:quests/quidditch_mischief_completed
advancement grant @s[scores={completedQuestID=66}] only hp:quests/quidditch_mischief_completed
advancement revoke @s[scores={completedQuestID=67}] only hp:quests/just_business_completed
advancement grant @s[scores={completedQuestID=67}] only hp:quests/just_business_completed
advancement revoke @s[scores={completedQuestID=68}] only hp:quests/bubotuber_burglary_completed
advancement grant @s[scores={completedQuestID=68}] only hp:quests/bubotuber_burglary_completed
advancement revoke @s[scores={completedQuestID=69}] only hp:quests/demiguise_dodge_completed
advancement grant @s[scores={completedQuestID=69}] only hp:quests/demiguise_dodge_completed
advancement revoke @s[scores={completedQuestID=71}] only hp:quests/a_lovely_letter_completed
advancement grant @s[scores={completedQuestID=71}] only hp:quests/a_lovely_letter_completed
advancement revoke @s[scores={completedQuestID=72}] only hp:quests/illegal_items_completed
advancement grant @s[scores={completedQuestID=72}] only hp:quests/illegal_items_completed


scoreboard players set @s completedQuestID 0

tag @s remove delayedQuestAdvancementOneFrame
tag @s add dontDelayQuestAdvancementOneFrameAgain