execute as @s[scores={InvSelectItemID=113},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/113
execute as @s[scores={InvSelectItemID=114},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/114
execute as @s[scores={InvSelectItemID=115},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/115
execute as @s[scores={InvSelectItemID=116},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/116
execute as @s[scores={InvSelectItemID=117},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/117
execute as @s[scores={InvSelectItemID=118},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/118
execute as @s[scores={InvSelectItemID=119},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/119
execute as @s[scores={InvSelectItemID=120},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/120
execute as @s[scores={InvSelectItemID=121},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/121
execute as @s[scores={InvSelectItemID=122},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/122
execute as @s[scores={InvSelectItemID=123},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/123
execute as @s[scores={InvSelectItemID=124},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/124
execute as @s[scores={InvSelectItemID=125},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/125
execute as @s[scores={InvSelectItemID=126},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/126
execute as @s[scores={InvSelectItemID=127},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/127
execute as @s[scores={InvSelectItemID=128},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/128
execute as @s[scores={InvSelectItemID=129},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/129
execute as @s[scores={InvSelectItemID=130},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/130
execute as @s[scores={InvSelectItemID=131},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/131
execute as @s[scores={InvSelectItemID=132},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/132
execute as @s[scores={InvSelectItemID=133},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/133
execute as @s[scores={InvSelectItemID=134},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/134
execute as @s[scores={InvSelectItemID=135},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/135
execute as @s[scores={InvSelectItemID=136},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/136
execute as @s[scores={InvSelectItemID=137},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/137
execute as @s[scores={InvSelectItemID=138},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/138
execute as @s[scores={InvSelectItemID=139},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/139
execute as @s[scores={InvSelectItemID=140},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/140
execute as @s[scores={InvSelectItemID=141},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/141
execute as @s[scores={InvSelectItemID=142},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/142
execute as @s[scores={InvSelectItemID=143},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/143
execute as @s[scores={InvSelectItemID=144},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/144
execute as @s[scores={InvSelectItemID=145},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/145
execute as @s[scores={InvSelectItemID=146},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/146
execute as @s[scores={InvSelectItemID=147},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/147
execute as @s[scores={InvSelectItemID=148},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/148
execute as @s[scores={InvSelectItemID=149},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/149
execute as @s[scores={InvSelectItemID=150},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/150
execute as @s[scores={InvSelectItemID=151},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/151
execute as @s[scores={InvSelectItemID=152},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/152
execute as @s[scores={InvSelectItemID=153},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/153
execute as @s[scores={InvSelectItemID=154},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/154
execute as @s[scores={InvSelectItemID=155},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/155
execute as @s[scores={InvSelectItemID=156},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/156
execute as @s[scores={InvSelectItemID=157},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/157
execute as @s[scores={InvSelectItemID=158},tag=!moveToQuickSlot,tag=!invTutorial] run function hp:draw_hotbar/draw_inventory_item/158