execute as @s[tag=!playerIsInvisible,tag=play] run function hp:inventory/equipment/clothes

# Give knockback Resistance level to prevent a weird bug that makes the player shoot into the air while and shortly after they've had the levitation effect
function hp:misc/prevent_levitation_bug



# Player is invisible
execute as @s[scores={levitationBug=0},tag=!earmuffs,tag=playerIsInvisible,tag=!letterbox,nbt=!{Inventory:[{Slot:103b,id:"minecraft:golden_hoe",Unbreakable:1b,Damage:32,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}]}]}] run replaceitem entity @s armor.head minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Unbreakable:1b,Damage:32,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}],HideFlags:63}
execute as @s[scores={levitationBug=0},tag=!earmuffs,tag=playerIsInvisible,tag=letterbox,nbt=!{Inventory:[{Slot:103b,id:"minecraft:carved_pumpkin",AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}],ench:[{id:10,lvl:1}]}]}] run replaceitem entity @s armor.head minecraft:carved_pumpkin{display:{Name:"{\"text\":\" \"}"},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}],ench:[{id:10,lvl:1}],HideFlags:63} 1
execute as @s[scores={levitationBug=1..},tag=!earmuffs,tag=playerIsInvisible,tag=!letterbox,nbt=!{Inventory:[{Slot:103b,id:"minecraft:golden_hoe",Unbreakable:1b,Damage:32,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}]}]}] run replaceitem entity @s armor.head minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Unbreakable:1b,Damage:32,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}],HideFlags:63}
execute as @s[scores={levitationBug=1..},tag=!earmuffs,tag=playerIsInvisible,tag=letterbox,nbt=!{Inventory:[{Slot:103b,id:"minecraft:carved_pumpkin",AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}],ench:[{id:10,lvl:1}]}]}] run replaceitem entity @s armor.head minecraft:carved_pumpkin{display:{Name:"{\"text\":\" \"}"},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}],ench:[{id:10,lvl:1}],HideFlags:63} 1
execute as @s[tag=playerIsInvisible,nbt={Inventory:[{Slot:102b}]}] run replaceitem entity @s armor.chest air
execute as @s[tag=playerIsInvisible,nbt={Inventory:[{Slot:101b}]}] run replaceitem entity @s armor.legs air
execute as @s[tag=playerIsInvisible,nbt={Inventory:[{Slot:100b}]}] run replaceitem entity @s armor.feet air

# Wearing earmuffs
execute as @s[scores={levitationBug=0},tag=!playerIsInvisible,tag=earmuffs,nbt=!{Inventory:[{Slot:103b,id:"minecraft:wooden_sword",Unbreakable:1b,Damage:18,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}]}]}] run replaceitem entity @s armor.head minecraft:wooden_sword{display:{Name:"{\"text\":\" \"}"},Unbreakable:1b,Damage:18,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}],HideFlags:63}
execute as @s[scores={levitationBug=1..},tag=!playerIsInvisible,tag=earmuffs,nbt=!{Inventory:[{Slot:103b,id:"minecraft:wooden_sword",Unbreakable:1b,Damage:18,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}]}]}] run replaceitem entity @s armor.head minecraft:wooden_sword{display:{Name:"{\"text\":\" \"}"},Unbreakable:1b,Damage:18,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}],HideFlags:63}

# clear if not in use
execute as @s[scores={levitationBug=0},tag=!earmuffs,tag=!playerIsInvisible,tag=!clothesReplaceSlot1,tag=!letterbox,nbt=!{Inventory:[{Slot:103b,id:"minecraft:golden_hoe",Unbreakable:1b,Damage:32,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}]}]}] run replaceitem entity @s armor.head minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Unbreakable:1b,Damage:32,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}],HideFlags:63}
execute as @s[scores={levitationBug=0},tag=!earmuffs,tag=!playerIsInvisible,tag=!clothesReplaceSlot1,tag=letterbox,nbt=!{Inventory:[{Slot:103b,id:"minecraft:carved_pumpkin",AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}],ench:[{id:10,lvl:1}]}]}] run replaceitem entity @s armor.head minecraft:carved_pumpkin{display:{Name:"{\"text\":\" \"}"},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945}],ench:[{id:10,lvl:1}],HideFlags:63} 1
execute as @s[scores={levitationBug=1..},tag=!earmuffs,tag=!playerIsInvisible,tag=!clothesReplaceSlot1,tag=!letterbox,nbt=!{Inventory:[{Slot:103b,id:"minecraft:golden_hoe",Unbreakable:1b,Damage:32,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}]}]}] run replaceitem entity @s armor.head minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Unbreakable:1b,Damage:32,AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}],HideFlags:63}
execute as @s[scores={levitationBug=1..},tag=!earmuffs,tag=!playerIsInvisible,tag=!clothesReplaceSlot1,tag=letterbox,nbt=!{Inventory:[{Slot:103b,id:"minecraft:carved_pumpkin",AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}],ench:[{id:10,lvl:1}]}]}] run replaceitem entity @s armor.head minecraft:carved_pumpkin{display:{Name:"{\"text\":\" \"}"},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:680,Operation:0,UUIDLeast:523105,UUIDMost:463945},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:99999999,Operation:0,UUIDLeast:394022,UUIDMost:196456}],ench:[{id:10,lvl:1}],HideFlags:63} 1
execute as @s[tag=!playerIsInvisible,tag=!clothesReplaceSlot2,nbt={Inventory:[{Slot:102b}]}] run replaceitem entity @s armor.chest air
execute as @s[tag=!playerIsInvisible,tag=!clothesReplaceSlot3,nbt={Inventory:[{Slot:101b}]}] run replaceitem entity @s armor.legs air
execute as @s[tag=!playerIsInvisible,tag=!clothesReplaceSlot4,nbt={Inventory:[{Slot:100b}]}] run replaceitem entity @s armor.feet air


# Quickslot tools
scoreboard players remove @s[scores={cloudInABottle=1..}] cloudInABottle 1
scoreboard players remove @s[scores={fireworks=1..}] fireworks 1
scoreboard players remove @s[scores={dungbomb=1..}] dungbomb 1
scoreboard players remove @s[scores={placeBroomTimer=1..}] placeBroomTimer 1