execute as @s[tag=!anim_playing,tag=anim_playingAlohomora] run tag @s add anim_playing

execute as @s[tag=anim_alohomora,scores={animTest=26,selectedSpell=4}] at @s run playsound minecraft:custom.spell.alohomora.cast master @a ~ ~ ~
execute as @s[tag=anim_alohomora,scores={animTest=26,selectedSpell=3}] at @s run playsound minecraft:custom.spell.brackium.brackium_emendo_summon master @a ~ ~ ~
execute as @s[tag=anim_alohomora,scores={animTest=26,selectedSpell=3}] at @s run playsound minecraft:custom.spell.brackium.brackium_emendo_loop master @a ~ ~ ~
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=26}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:210}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=25}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:209}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=24}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:208}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=23}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:207}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=22}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:206}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=21}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:205}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=20}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:204}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=19}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:203}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=18}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:202}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=17}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:201}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=16}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:200}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=15}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:199}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=14}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:198}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=13}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:197}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=12}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:196}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=11}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:195}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=10}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:194}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=9}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:193}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=8}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:192}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=7}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:191}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=6}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:190}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=5}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:189}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=4}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:188}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=3}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:187}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=2}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:186}
replaceitem entity @s[tag=anim_playingAlohomora,scores={animTest=1}] hotbar.0 minecraft:iron_sword{AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,Damage:185}

execute as @s[tag=anim_playingAlohomora,scores={animTest=1}] run function hp:spells/spell/cast_alohomora
execute as @s[tag=anim_playingAlohomora,scores={animTest=1}] run tag @s remove anim_playing
execute as @s[tag=anim_playingAlohomora,scores={animTest=1}] run tag @s remove anim_alohomora
execute as @s[tag=anim_playingAlohomora,scores={animTest=1}] run tag @s remove anim_playingAlohomora