# Fade to black when in lumos transition area
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:23}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=4.75..5.5] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:23,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:12}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=4.5..4.75] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:12,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:11}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=4.25..4.5] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:11,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:10}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=4..4.25] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:10,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:9}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=3.75..4] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:9,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:8}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=3.5..3.75] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:8,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:7}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=3.25..3.5] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:7,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:6}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=3..3.25] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:6,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:5}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=2.75..3] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:5,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:4}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=2.5..2.75] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:4,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:3}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=2.25..2.5] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:3,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:2}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=2..2.25] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:2,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:1}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=1.75..2] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:1,qDetect:1b,fDetect:1b}
execute at @s[tag=!inLumos,tag=!lumosScreenFade,tag=!inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:0}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=0..1.75] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:0,qDetect:1b,fDetect:1b}

execute at @s[tag=!inTravelPoint,tag=!inLumos,tag=!lumosScreenFade,tag=inLumosAir,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:0}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:0,fDetect:1b}
execute at @s[tag=!inTravelPoint,tag=inLumos,tag=!lumosScreenFade,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:23}}]}] if entity @e[tag=lumosEnterArea,limit=1,sort=nearest,distance=5.5..] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:23,fDetect:1b}
execute as @s[tag=!inTravelPoint,tag=lumosScreenFade,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:13}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \"}"},Unbreakable:1,Damage:13,fDetect:1b}