# I realize it's not called cape - English is my second language and in Danish cloak and cape is the same word. I realized too late, and not I can't be bothered to change all the references.

# Vignette animation
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}
replaceitem entity @s[scores={invisCapeAnim=..1},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:10}

replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}
replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}
replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}
replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}
replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}
replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}
replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}
replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}
replaceitem entity @s[scores={invisCapeAnim=2},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:9}

replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}
replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}
replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}
replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}
replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}
replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}
replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}
replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}
replaceitem entity @s[scores={invisCapeAnim=3},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:8}

replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}
replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}
replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}
replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}
replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}
replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}
replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}
replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}
replaceitem entity @s[scores={invisCapeAnim=4},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:7}

replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}
replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}
replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}
replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}
replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}
replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}
replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}
replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}
replaceitem entity @s[scores={invisCapeAnim=5},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:6}

replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}
replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}
replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}
replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}
replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}
replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}
replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}
replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}
replaceitem entity @s[scores={invisCapeAnim=6},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:5}

replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}
replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}
replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}
replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}
replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}
replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}
replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}
replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}
replaceitem entity @s[scores={invisCapeAnim=7},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:4}

replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}
replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}
replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}
replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}
replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}
replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}
replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}
replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}
replaceitem entity @s[scores={invisCapeAnim=8},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:3}

replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}
replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}
replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}
replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}
replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}
replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}
replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}
replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}
replaceitem entity @s[scores={invisCapeAnim=9},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:2}

replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.0 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}
replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.1 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}
replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.2 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}
replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.3 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}
replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.4 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}
replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.5 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}
replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.6 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}
replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.7 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}
replaceitem entity @s[scores={invisCapeAnim=10},tag=!usingInvisibilityPotion,tag=!usedInvisibilityPotion] hotbar.8 minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:1}

# Empty
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.0 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.1 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.2 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.3 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.4 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.5 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.6 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.7 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=usingInvisibilityPotion] hotbar.8 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}

# Empty
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.0 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.1 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.2 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.3 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.4 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.5 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.6 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.7 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s[tag=!usingInvisibilityPotion,tag=usedInvisibilityPotion] hotbar.8 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}

# Empty offhand
replaceitem entity @s[nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_hoe",tag:{Damage:32}}]},tag=!usingInvisibilityPotion] weapon.offhand minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:32,fDetect:1b}
# Vignette offhand
replaceitem entity @s[nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:14}}]},tag=usingInvisibilityPotion] weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:14,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}