# Draw spell selection menu



# Hidden
replaceitem entity @s[scores={animTest=1..}] hotbar.0 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={animTest=1..}] hotbar.1 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={animTest=1..}] hotbar.2 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={animTest=1..}] hotbar.3 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={animTest=1..}] hotbar.4 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={animTest=1..}] hotbar.5 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={animTest=1..}] hotbar.6 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={animTest=1..}] hotbar.7 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={animTest=1..}] hotbar.8 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

# Enter animation
replaceitem entity @s[scores={animTest=0},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:27}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:27,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=1},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:25}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:25,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=2},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:23}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:23,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=3},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:21}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:21,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=4},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:19}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:19,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=5},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:17}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:17,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=6},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:15}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:15,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=7},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:13}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:13,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}

# Potions
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.0 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.1 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.2 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.3 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.4 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.5 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.6 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.7 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=1,animTest=0}] hotbar.8 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:245,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.0 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.1 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.2 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.3 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.4 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.5 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.6 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.7 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=2,animTest=0}] hotbar.8 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:244,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.0 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.1 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.2 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.3 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.4 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.5 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.6 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.7 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=3,animTest=0}] hotbar.8 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:243,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.0 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.1 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.2 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.3 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.4 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.5 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.6 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.7 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=4,animTest=0}] hotbar.8 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:242,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.0 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.1 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.2 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.3 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.4 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.5 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.6 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.7 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=5,animTest=0}] hotbar.8 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:241,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.0 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.1 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.2 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.3 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.4 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.5 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.6 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.7 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=6,animTest=0}] hotbar.8 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:239,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.0 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.1 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.2 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.3 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.4 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.5 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.6 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.7 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=7,animTest=0}] hotbar.8 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:240,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.0 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.1 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.2 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.3 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.4 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.5 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.6 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.7 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
replaceitem entity @s[scores={selectCurrent=8,animTest=0}] hotbar.8 minecraft:iron_pickaxe{display:{Name:"{\"text\":\" \"}"},Damage:238,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

tag @s[scores={animTest=0}] remove letterbox