# Enter animation
replaceitem entity @s[scores={animTest=0},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:27}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:27,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=1},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:25}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:25,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=2},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:23}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:23,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=3},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:21}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:21,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=4},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:19}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:19,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=5},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:17}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:17,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=6},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:15}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:15,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}
replaceitem entity @s[scores={animTest=7},tag=!inConversation,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:13}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:13,Unbreakable:1b,qDetect:1b,fDetect:1b,HideFlags:63}

tag @s[scores={animTest=6}] remove letterbox


# Hidden
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.0 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.1 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.2 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.3 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.4 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.5 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.6 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.7 minecraft:golden_hoe{Damage:28,Unbreakable:1b,display:{Name:"{\"text\":\" \"}"},qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute unless score @s convState matches 2 run replaceitem entity @s hotbar.8 minecraft:golden_hoe{display:{Name:"{\"text\":\" \"}"},Damage:32,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=1}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:30,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=2}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:29,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=3}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:26,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=4}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:27,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=5}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:1,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=6}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:3,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=7}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:2,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=8}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:28,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}

execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.0 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.1 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.2 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.3 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.4 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.5 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.6 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.7 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}
execute as @s[scores={convState=2,selectCurrent=9}] run replaceitem entity @s hotbar.8 minecraft:golden_axe{display:{Name:"{\"text\":\" \"}"},Damage:5,Unbreakable:1b,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],HideFlags:63}