# Clear Hotbar
# Wand animation
execute as @s[tag=!isApparating] run function hp:animation/main_animation

execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.0 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}
execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.1 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}
execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.2 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}
execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.3 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}
execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.4 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}
execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.5 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}
execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.6 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}
execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.7 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}
execute as @s[tag=isApparating,scores={apparating=10..17}] run replaceitem entity @s hotbar.8 minecraft:golden_sword{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,qDetect:1b,AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-99999,Operation:0,UUIDLeast:277390,UUIDMost:248617}],Unbreakable:1b,Damage:13}

replaceitem entity @s[nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:14}}]}] weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},Damage:14,Unbreakable:1b,qDetect:1b,fDetect:1b}

