replaceitem entity @s hotbar.0 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s hotbar.1 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s hotbar.2 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s hotbar.3 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s hotbar.4 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s hotbar.5 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s hotbar.6 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s hotbar.7 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}
replaceitem entity @s hotbar.8 minecraft:golden_hoe{display:{Name:"{\"text\":\" \",\"color\":\"gold\",\"bold\":true}"},HideFlags:63,Damage:32,Unbreakable:1b,qDetect:1b}

# Fade animation - Controlled in "fast_travel"
replaceitem entity @s[scores={fastTravelTimer=99},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:12}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:12,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=98},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:13}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:13,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=97},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:14}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:14,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=95},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:16}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:15,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=96},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:15}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:16,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=94},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:17}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:17,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=93},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:18}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:18,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=92},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:19}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:19,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=91},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:20}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:20,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=90},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:21}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:21,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=89},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:22}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:22,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=88},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:23}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:23,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=87},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:24}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:24,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=86},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:25}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:25,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=85},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:26}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:26,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=84},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:27}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:27,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=83},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:28}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:28,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=82},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:29}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:29,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=81},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:30}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:30,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=80},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:31}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:31,fDetect:1b}

replaceitem entity @s[scores={fastTravelTimer=21..79},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:32}}]}] weapon.offhand minecraft:golden_pickaxe{HideFlags:63,Unbreakable:1,Damage:32,fDetect:1b}

replaceitem entity @s[scores={fastTravelTimer=20},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:31}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:31,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=19},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:30}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:30,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=18},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:29}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:29,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=17},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:28}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:28,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=16},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:27}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:27,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=15},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:26}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:26,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=14},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:25}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:25,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=13},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:24}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:24,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=12},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:23}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:23,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=11},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:22}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:22,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=10},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:21}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:21,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=9},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:20}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:20,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=8},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:19}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:19,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=7},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:18}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:18,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=6},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:17}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:17,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=5},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:16}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:16,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=4},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:15}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:15,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=3},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:14}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:14,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=2},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:13}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:13,fDetect:1b}
replaceitem entity @s[scores={fastTravelTimer=1},nbt=!{Inventory:[{Slot:-106b,id:"minecraft:golden_pickaxe",tag:{Damage:12}}]}] weapon.offhand minecraft:golden_pickaxe{display:{Name:"{\"text\":\" \"}"},HideFlags:63,Unbreakable:1,Damage:12,fDetect:1b}

# Clear potential cinematic bars
tag @s remove letterbox