execute as @s[scores={travelPoint=70},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:12}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:12,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=69},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:11}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:11,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=68},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:10}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:10,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=67},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:8}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:8,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=66},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:7}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:7,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=65},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:5}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:5,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=64},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:4}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:4,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=63},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:2}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:2,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=17..62},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:0}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:0,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=62}] at @s run tp @s 5483.63 81.00 2490.35 456.84 2.51
execute as @s[scores={travelPoint=9},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:2}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:2,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=8},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:3}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:3,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=7},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:4}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:4,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=6},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:6}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:6,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=5},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:7}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:7,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=3},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:9}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:9,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=2},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:10}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:10,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=1},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:11}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:11,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=0},tag=offhandCanBeReplaced,nbt=!{Inventory:[{Slot:-106b,id:"minecraft:carrot_on_a_stick",tag:{Damage:12}}]}] run replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:12,qDetect:1b,fDetect:1b}
execute as @s[scores={travelPoint=0}] run tag @s remove inTravelPoint
execute as @s[scores={travelPoint=0,trackedQuestID=1..},tag=!inLumosTransitionArea] run tag @s add silentQuestAnimation
execute as @s[scores={travelPoint=0,trackedQuestID=1..},tag=!inLumosTransitionArea] run tag @s add showTrackedQuest
execute as @s[scores={travelPoint=0}] run tag @s remove travelPointHoneydukesPassage