scoreboard players set @s armorSuitsK 0
scoreboard players set @s flobberwormsK 0
scoreboard players set @s darkSpiritsK 0
scoreboard players set @s darkWizardsK 0
scoreboard players set @s deathEatersK 0
scoreboard players set @s grindylowsK 0
scoreboard players set @s largeSpidersK 0
scoreboard players set @s smallSpidersK 0
scoreboard players set @s monsterBooksK 0
scoreboard players set @s murtlapsK 0
scoreboard players set @s pixieGnomesK 0
scoreboard players set @s poltergeistsK 0
scoreboard players set @s ratsK 0
scoreboard players set @s skeletonsK 0
scoreboard players set @s skeletonArchersK 0
scoreboard players set @s skeletonSwordsK 0
scoreboard players set @s toadsK 0
scoreboard players set @s trollsK 0
scoreboard players set @s flobberwormK 0