execute as @s[scores={nestType=1}] at @s run function hp:creatures/toad/toad_nest
execute as @s[scores={nestType=2}] at @s run function hp:creatures/murtlap/murtlap_nest
execute as @s[scores={nestType=3}] at @s run function hp:creatures/large_spider/large_spider_nest
execute as @s[scores={nestType=4}] at @s run function hp:creatures/small_spider/small_spider_nest
execute as @s[scores={nestType=5}] at @s run function hp:creatures/flubberworm/flubberworm_nest
execute as @s[scores={nestType=6}] at @s run function hp:creatures/rat/rat_nest
execute as @s[scores={nestType=7}] at @s run function hp:creatures/troll/troll_nest
execute as @s[scores={nestType=8}] at @s run function hp:creatures/death_eater/death_eater_nest
execute as @s[scores={nestType=9}] at @s run function hp:creatures/pixie_gnome/pixie_nest
execute as @s[scores={nestType=10}] at @s run function hp:creatures/monster_book/monster_book_nest
execute as @s[scores={nestType=11}] at @s run function hp:creatures/armor_suit/armor_suit_nest
execute as @s[scores={nestType=12}] at @s run function hp:creatures/skeleton/skeleton_nest
execute as @s[scores={nestType=13}] at @s run function hp:creatures/skeleton_archer/skeleton_archer_nest
execute as @s[scores={nestType=14}] at @s run function hp:creatures/skeleton_swordsman/skeleton_swordsman_nest
execute as @s[scores={nestType=15}] at @s run function hp:creatures/grindylow/grindylow_nest
execute as @s[scores={nestType=16}] at @s run function hp:creatures/poltergeist/poltergeist_nest