execute if entity @s[scores={InvItemID=113}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/dungbomb
execute if entity @s[scores={InvItemID=114}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/beaters_bat
execute if entity @s[scores={InvItemID=115}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/axe
execute if entity @s[scores={InvItemID=116}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/rusty_sword
execute if entity @s[scores={InvItemID=117}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/fancy_sword
execute if entity @s[scores={InvItemID=118}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/sword_of_gryffindor
execute if entity @s[scores={InvItemID=119}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/sting
execute if entity @s[scores={InvItemID=120}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/self_shuffling_playing_cards
execute if entity @s[scores={InvItemID=121}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/anti_cheating_quill
execute if entity @s[scores={InvItemID=122}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/spell_checking_quill
execute if entity @s[scores={InvItemID=123}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/quick_quotes_quill
execute if entity @s[scores={InvItemID=124}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/crystal_ball
execute if entity @s[scores={InvItemID=125}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/floo_powder
execute if entity @s[scores={InvItemID=126}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/advanced_rune_translation
execute if entity @s[scores={InvItemID=127}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/a_history_of_magic
execute if entity @s[scores={InvItemID=128}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/unfogging_the_future
execute if entity @s[scores={InvItemID=129}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/ancient_runes_made_easy
execute if entity @s[scores={InvItemID=130}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/magical_theory
execute if entity @s[scores={InvItemID=131}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/secrets_of_the_darkest_art
execute if entity @s[scores={InvItemID=132}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/the_lady_of_the_lake
execute if entity @s[scores={InvItemID=133}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/living_with_legilimens
execute if entity @s[scores={InvItemID=134}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/spells_and_enchantments_for_the_human_species
execute if entity @s[scores={InvItemID=135}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/1000_magical_herbs_and_fungi
execute if entity @s[scores={InvItemID=136}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/magical_water_plants_of_the_mediterranean
execute if entity @s[scores={InvItemID=137}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/quidditch_through_the_ages
execute if entity @s[scores={InvItemID=138}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/armando_dippet_master_or_moron
execute if entity @s[scores={InvItemID=139}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/the_witching_hour
execute if entity @s[scores={InvItemID=140}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/from_the_earth_to_the_moon
execute if entity @s[scores={InvItemID=141}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/gilderoy_lockharts_guide_to_household_pests
execute if entity @s[scores={InvItemID=142}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/palmistry_guide
execute if entity @s[scores={InvItemID=143}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/mudbloods_and_how_to_spot_them
execute if entity @s[scores={InvItemID=144}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/the_flap_of_the_cape
execute if entity @s[scores={InvItemID=145}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/when_muggles_attack
execute if entity @s[scores={InvItemID=146}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/magical_me
execute if entity @s[scores={InvItemID=147}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/bludger
execute if entity @s[scores={InvItemID=148}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/quaffle
execute if entity @s[scores={InvItemID=149}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/pixie_wings
execute if entity @s[scores={InvItemID=150}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/rat_tail
execute if entity @s[scores={InvItemID=151}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/troll_toe
execute if entity @s[scores={InvItemID=152}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/murtlap_tentacle
execute if entity @s[scores={InvItemID=153}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/flobberworm_mucus
execute if entity @s[scores={InvItemID=154}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/acromantula_venom
execute if entity @s[scores={InvItemID=155}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/mysterious_coconut
execute if entity @s[scores={InvItemID=156}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/skull
execute if entity @s[scores={InvItemID=157}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/lime_green_bowler_hat
execute if entity @s[scores={InvItemID=158}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/troll_fat