execute if entity @s[scores={InvItemID=38}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/invisibility_cloak
execute if entity @s[scores={InvItemID=39}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/fantastic_beasts
execute if entity @s[scores={InvItemID=40}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/standard_book_of_spells
execute if entity @s[scores={InvItemID=41}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/magical_drafts_and_potions
execute if entity @s[scores={InvItemID=42}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/dark_forces
execute if entity @s[scores={InvItemID=43}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/guide_to_transfiguration
execute if entity @s[scores={InvItemID=44}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/tales_of_beedle_bard
execute if entity @s[scores={InvItemID=45}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/spectrespecs
execute if entity @s[scores={InvItemID=46}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/bundle_of_fluxweed
execute if entity @s[scores={InvItemID=47}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/gilly_weed
execute if entity @s[scores={InvItemID=48}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/cup_of_salt
execute if entity @s[scores={InvItemID=49}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/cup_of_sugar
execute if entity @s[scores={InvItemID=50}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/bundle_of_hair
execute if entity @s[scores={InvItemID=51}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/demiguise_hair
execute if entity @s[scores={InvItemID=52}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/eyeball
execute if entity @s[scores={InvItemID=53}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/toad_brain
execute if entity @s[scores={InvItemID=54}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/jar_of_leeches
execute if entity @s[scores={InvItemID=55}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/bone_powder
execute if entity @s[scores={InvItemID=56}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/black_powder
execute if entity @s[scores={InvItemID=57}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/green_powder
execute if entity @s[scores={InvItemID=58}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/red_powder
execute if entity @s[scores={InvItemID=59}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/yellow_powder
execute if entity @s[scores={InvItemID=60}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/blue_powder
execute if entity @s[scores={InvItemID=61}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/pearl_dust
execute if entity @s[scores={InvItemID=62}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/vial_of_puke
execute if entity @s[scores={InvItemID=63}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/dragon_blood
execute if entity @s[scores={InvItemID=64}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/dragon_scale
execute if entity @s[scores={InvItemID=65}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/flask
execute if entity @s[scores={InvItemID=66}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/vial
execute if entity @s[scores={InvItemID=67}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/string
execute if entity @s[scores={InvItemID=68}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/linnen_cloth
execute if entity @s[scores={InvItemID=69}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/parchment
execute if entity @s[scores={InvItemID=70}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/remembrall
execute if entity @s[scores={InvItemID=71}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/wizard_card
execute if entity @s[scores={InvItemID=72}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/green_magic_gem
execute if entity @s[scores={InvItemID=73}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/blue_magic_gem
execute if entity @s[scores={InvItemID=74}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/red_magic_gem
execute if entity @s[scores={InvItemID=75}] as @e[type=armor_stand,tag=focusInventoryOption,limit=1] run function hp:inventory/inv_items/silver_mug